### ISSUE TITLE
Issue #2

### ISSUE THREAD

**Issue by SeongKookKIM** [APP-iOS5th/FinalProject-RideThis#21]
### <로그아웃>
- 로그아웃 상태일때 로그인 후 사용해주세요 문구 있으면 좋을거 같습니당
- 로그아웃 상태일때 하단에 그래프 및 텍스트 어떻게 할건지에 대하여..?
- 로그아웃 상태에서 설정-비공개 설정 토글 먹혀유ㅠㅠ
- 로그아웃 상태일시 설정 계정정보의 로그아웃 회원탈퇴 페이지 나와유

### <로그인>
- 다시 로그인 하면 정보 추가 또 나옴(다음 누르면 앱터져유..ㅠㅠ)

## 기록 페이지

- 기록 시작- 중지 시에 에도 리셋, 기록종료 버튼 활성화 되어야 할거 같습니다 또는 정지 상태에서만 활성화..? 이 부분은 한번 더 이야기해봐유~

**Comment by KyuShark** [comment]
사랑해요~
